
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: code_mcp:latest
    container_name: code_mcp
    restart: unless-stopped
    environment:
      - ENV=production
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: code_mcp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: code_mcp
      POSTGRES_USER: code_mcp_user
      POSTGRES_PASSWORD: code_mcp_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: code_mcp_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@code-mcp.local
      PGADMIN_DEFAULT_PASSWORD: admin_pass
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge

volumes:
  data:
  postgres_data:
  pgadmin_data:
